### ISSUE TITLE
When i use the region growth algorithm to segment powerline，how can i get seed cloud from my ".las" point cloud ?

### ISSUE THREAD

**Issue by zlei96** [mcserep/railroad#1]

**Comment by mcserep** [comment]
Hello,

The seed must be manually extracted by selecting a small segment of the powerline with a LAS editor tool like [CloudCompare](https://www.danielgm.net/cc/). A seed of few meters shall be enough.
(Creating the seed with another algorithm could also work.)

I can send you a sample railway segment and a powerline seed to it, which was used to the get the results showcased in the README file. However for your own dataset you must create the seed for yourself.

Also, I have added the link to the [master thesis](https://gis.inf.elte.hu/wordpress/wp-content/uploads/2020/07/mayer_friderika_msc_compressed.pdf) behind the region growth algorithm to the end of the README in case you are interested in the details.
