### ISSUE TITLE
Scans

### ISSUE THREAD

**Issue by naranjuelo** [mcserep/railroad#3]
Hi, thank you for sharing this great work! I'm interested in getting individual scans rather than the reconstructed point cloud. Is that possible? Could you share this information? Thank you in advance!

**Comment by mcserep** [comment]
Hi @naranjuelo,
The framework works on a constructed point cloud of a larger area as input, not on series of individual LiDAR scans. The latter case I believe would require different algorithms both in cable and rail detection and are not in our current plans to move towards.

**Comment by naranjuelo** [comment]
Understood. I am interested in working with single scans so I would use different methods. I was wondering if you have that single scan data and if it would be sharable. I have downloaded the dataset from this page https://data.mendeley.com/datasets/ccxpzhx9dj

**Comment by mcserep** [comment]
I understand now. I would gladly give you the single scan data, but unfortunately we don't have that available, only the already constructed larger point clouds which you have found.

**Comment by naranjuelo** [comment]
Okay, thank you anyway!
