### ISSUE TITLE
issue opencv

### ISSUE THREAD

**Issue by ASSEKO10** [mcserep/railroad#4]
hello MATÉ, i am working on your railroad detection algo , i got issues by executing the algo, i got this message << terminate called after throwing an instance of 'cv::Exception'
 what(): OpenCV(4.5.4) ./modules/core/src/matrix_wrap.cpp:1667: error: (-215:Assertion failed) !fixedSize() in function 'release'>> 
i seriously need your help to fix that issue. feel free to write in private.

have a good day

**Comment by yuancaimaiyi** [comment]
@ASSEKO10  Hi,did you solve this problem?

**Comment by mcserep** [comment]
Hi @ASSEKO10 and @yuancaimaiyi,

Sorry for the late response, I had little time for this project recently. I guess the question is not actual anymore, but I will answer it in case someone is directed here in the future.

The mentioned error is most likely the result of the algorithm not-detecting the rail pairs correctly. In case there are 0 detected points for the railbed, the 2.5D projection by OpenCV produces this assertion warning. Possible solutions are:
 - Try to manually cut out the railbed a bit more precisely, with minimal surroundings, so the algorithm will find it easier.
 - Use the seeded version of then rail track detection (`RailTrackWithSeed` algorithm pipeline), in which case the detected cables are passed to the rail detection to better locate the rails afterwards.
