### ISSUE TITLE
 Test Data？

### ISSUE THREAD

**Issue by yuancaimaiyi** [mcserep/railroad#5]
@mcserep 
Hello,great work!  Can you provide some test data, thank you very much!

**Comment by mcserep** [comment]
Hi @yuancaimaiyi,
Thanks! Fortunately, as part of our journal publication in 2022, we were allowed to publish a few shorter segments of the full processed dataset by the Hungarian State Railways. The data was published in Mendeley Data:  

Cserep, Mate (2022), *“Hungarian MLS point clouds of railroad environment and annotated ground truth data”*, Mendeley Data, V1, [DOI: 10.17632/ccxpzhx9dj.1](http://dx.doi.org/10.17632/ccxpzhx9dj.1)

These are the datasets, which were showcased in the following publication:
Máté Cserép, Adalbert Demján, Friderika Mayer, Tábori Balázs, Péter Hudoba: *Effective Railroad Fragmentation And Infrastructure Recognition Based On Dense LiDAR Point Clouds*, ISPRS Ann. Photogramm. Remote Sens. Spatial Inf. Sci., V-2-2022, pp. 103–109, 2022, [DOI: 10.5194/isprs-annals-V-2-2022-103-2022](https://doi.org/10.5194/isprs-annals-V-2-2022-103-2022)
